### ISSUE TITLE
Unhandled rejection Error: Transaction was not mined within 50 blocks, please make sure your transaction was properly send. Be aware that it might still be mined!

### ISSUE THREAD

**Issue by adv0r** [0xbitcoin/0xbitcoin-token#3]
Hash rate: 3927.6
```
    at /Users/advanced/Desktop/0xbitcoin-miner/node_modules/web3-core-method/src/index.js:375:45
    at tryCatcher (/Users/advanced/Desktop/0xbitcoin-miner/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/advanced/Desktop/0xbitcoin-miner/node_modules/bluebird/js/release/promise.js:497:31)
    at Promise._settlePromise (/Users/advanced/Desktop/0xbitcoin-miner/node_modules/bluebird/js/release/promise.js:555:18)
    at Promise._settlePromise0 (/Users/advanced/Desktop/0xbitcoin-miner/node_modules/bluebird/js/release/promise.js:600:10)
    at Promise._settlePromises (/Users/advanced/Desktop/0xbitcoin-miner/node_modules/bluebird/js/release/promise.js:679:18)
    at Async._drainQueue (/Users/advanced/Desktop/0xbitcoin-miner/node_modules/bluebird/js/release/async.js:125:16)
    at Async._drainQueues (/Users/advanced/Desktop/0xbitcoin-miner/node_modules/bluebird/js/release/async.js:135:10)
    at Immediate.Async.drainQueues (/Users/advanced/Desktop/0xbitcoin-miner/node_modules/bluebird/js/release/async.js:16:14)
    at runCallback (timers.js:756:18)
    at tryOnImmediate (timers.js:717:5)
    at processImmediate [as _immediateCallback] (timers.js:697:5)
```

**Comment by 0xbitcoin** [comment]
Hello this is a standard web3 warning that is just telling you that the TX was not mined very fast and you may need higher gas price.  Competition had become fierce.  You can set it with

Config gasprice 20

For example
